### ISSUE TITLE
Feature Request: Support Ingress

### ISSUE THREAD

**Issue by tinybighuman** [hassio-addons/addon-overseerr#11] opened 2024-05-06 12:33 UTC
# Problem/Motivation

Addon is not accessible outside of the local network and cannot be accessed through Nabu Casa's URL.

## Expected behavior

Addon supports the ingress capability and can be accessed when outside of the home network using Nabu Casa's assigned URL.

## Actual behavior

Addon is not accessible from non-local url.

## Steps to reproduce

1. Install and setup the addon.
2. Switch from local network to another network or mobile internet.
3. Navigate to the Addon's page
4. Open Overseerr page
5. Click on "Open Web UI" button.

**Comment by frenck** [comment] 2024-05-06 12:44
Closing this, as this is not a bug. Feel free to help develop the add-on in adding new features.

../Frenck

**Closed as not planned by frenck** 2024-05-06 12:44 UTC
